// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarMatrix.Models;

namespace StarMatrix.Migrations
{
    [DbContext(typeof(StarMatrixContext))]
    [Migration("20191111073835_test12")]
    partial class test12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarMatrix.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Ipaddress");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Roles")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("StarMatrix.Models.BollardPull", b =>
                {
                    b.Property<int>("BollardPullId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BollardPullName")
                        .IsRequired();

                    b.HasKey("BollardPullId");

                    b.ToTable("BollardPull");
                });

            modelBuilder.Entity("StarMatrix.Models.ClassType", b =>
                {
                    b.Property<int>("ClassTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassTypeName")
                        .IsRequired();

                    b.HasKey("ClassTypeId");

                    b.ToTable("ClassType");
                });

            modelBuilder.Entity("StarMatrix.Models.EngineHP", b =>
                {
                    b.Property<int>("EngineHPId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EngineHPName")
                        .IsRequired();

                    b.HasKey("EngineHPId");

                    b.ToTable("EngineHP");
                });

            modelBuilder.Entity("StarMatrix.Models.ShipLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Availability")
                        .IsRequired();

                    b.Property<string>("AvailableLocation")
                        .IsRequired();

                    b.Property<DateTime?>("DateAdded");

                    b.Property<string>("Ipaddress");

                    b.Property<string>("PresentLocation")
                        .IsRequired();

                    b.Property<int>("TugId");

                    b.HasKey("Id");

                    b.HasIndex("TugId");

                    b.ToTable("ShipLocation");
                });

            modelBuilder.Entity("StarMatrix.Models.Tug", b =>
                {
                    b.Property<int>("TugId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BollardPullName")
                        .IsRequired();

                    b.Property<string>("ClassTypeName")
                        .IsRequired();

                    b.Property<string>("EngineHPName")
                        .IsRequired();

                    b.Property<string>("TugName")
                        .IsRequired();

                    b.HasKey("TugId");

                    b.ToTable("Tug");
                });

            modelBuilder.Entity("StarMatrix.Models.ShipLocation", b =>
                {
                    b.HasOne("StarMatrix.Models.Tug", "Tugs")
                        .WithMany()
                        .HasForeignKey("TugId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
